# -*- coding: utf-8 -*-
"""Crop_Disease_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sJ641I0Jub78yeXx8Hz-zKOVw-3A1HPd
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
import matplotlib.pyplot as plt
import numpy as np

!pip install kagglehub

import kagglehub

path = kagglehub.dataset_download("emmarex/plantdisease")

print("Path to dataset files:", path)

import os
os.listdir(path)

dataset_path = "/kaggle/input/plantdisease/PlantVillage"

train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_generator = train_datagen.flow_from_directory(
    dataset_path,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='training'
)

val_generator = train_datagen.flow_from_directory(
    dataset_path,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    subset='validation'
)

model = Sequential()

model.add(Conv2D(32, (3,3), activation='relu', input_shape=(224,224,3)))
model.add(MaxPooling2D(2,2))

model.add(Conv2D(64, (3,3), activation='relu'))
model.add(MaxPooling2D(2,2))

model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(train_generator.num_classes, activation='softmax'))

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=5
)

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model

base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_shape=(224,224,3)
)

base_model.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.3)(x)
output = Dense(train_generator.num_classes, activation='softmax')(x)

model2 = Model(inputs=base_model.input, outputs=output)

model2.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model2.summary()

history2 = model2.fit(
    train_generator,
    validation_data=val_generator,
    epochs=5
)

import matplotlib.pyplot as plt

plt.plot(history2.history['accuracy'])
plt.plot(history2.history['val_accuracy'])
plt.title("Training vs Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend(["Train Accuracy", "Validation Accuracy"])

plt.savefig("training_accuracy.png") 
plt.show()

from google.colab import files
files.download("training_accuracy.png")

model2.save("final_crop_disease_model.h5")

from google.colab import files
files.download("final_crop_disease_model.h5")

from google.colab import files
uploaded = files.upload()

from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt

img = image.load_img("leaf_test.jpg", target_size=(224,224))

plt.imshow(img)
plt.axis("off")
plt.title("Uploaded Leaf")
plt.show()

img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array = img_array / 255.0

prediction = model2.predict(img_array)

predicted_class = np.argmax(prediction)
confidence = np.max(prediction)

class_labels = list(train_generator.class_indices.keys())

print("Predicted Disease:", class_labels[predicted_class])
print("Confidence:", confidence)

import matplotlib.pyplot as plt

disease_name = class_labels[predicted_class]

plt.imshow(img)
plt.axis("off")
plt.title(f"Prediction: {disease_name}\nConfidence: {confidence:.2f}")

plt.savefig("demo_prediction.png", bbox_inches="tight")

plt.show()

from google.colab import files
files.download("demo_prediction.png")